# Generated by Django 2.0.1 on 2024-06-18 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooftop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tel',
            new_name='sage',
        ),
    ]
