# Generated by Django 2.0.1 on 2024-06-21 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooftop', '0003_reserve'),
    ]

    operations = [
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=55)),
                ('subject', models.CharField(max_length=55)),
                ('message', models.CharField(max_length=255)),
            ],
        ),
    ]
