# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2024-06-22 13:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooftop', '0006_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='review',
        ),
    ]
